"""Small offline dataset (popular VGC Pokémon) so the app runs without internet.

Stats are official base stats; move lists are a representative subset only.
"""

MOVES = {  # name: (type, category, power)
    "earthquake": ("ground", "physical", 100), "dragon-claw": ("dragon", "physical", 80),
    "stone-edge": ("rock", "physical", 100), "flare-blitz": ("fire", "physical", 120),
    "knock-off": ("dark", "physical", 65), "fake-out": ("normal", "physical", 40),
    "wood-hammer": ("grass", "physical", 120), "grassy-glide": ("grass", "physical", 55),
    "u-turn": ("bug", "physical", 70), "sludge-bomb": ("poison", "special", 90),
    "giga-drain": ("grass", "special", 75), "spore": ("grass", "status", None),
    "extreme-speed": ("normal", "physical", 80), "dragon-dance": ("dragon", "status", None),
    "make-it-rain": ("steel", "special", 120), "shadow-ball": ("ghost", "special", 80),
    "kowtow-cleave": ("dark", "physical", 85), "iron-head": ("steel", "physical", 80),
    "sucker-punch": ("dark", "physical", 70), "rock-slide": ("rock", "physical", 75),
    "crunch": ("dark", "physical", 80), "high-horsepower": ("ground", "physical", 95), "hurricane": ("flying", "special", 110),
    "weather-ball": ("normal", "special", 50), "heat-wave": ("fire", "special", 95),
    "eruption": ("fire", "special", 150), "solar-beam": ("grass", "special", 120),
    "moonblast": ("fairy", "special", 95), "psychic": ("psychic", "special", 90),
    "brave-bird": ("flying", "physical", 120), "body-press": ("fighting", "physical", 80),
    "scald": ("water", "special", 80), "ice-beam": ("ice", "special", 90),
    "close-combat": ("fighting", "physical", 120), "dire-claw": ("poison", "physical", 80),
    "dragon-darts": ("dragon", "physical", 50), "phantom-force": ("ghost", "physical", 90),
    "blizzard": ("ice", "special", 110),
    "glaive-rush": ("dragon", "physical", 120), "icicle-crash": ("ice", "physical", 85),
    "electro-shot": ("electric", "special", 130), "draco-meteor": ("dragon", "special", 130),
    "flash-cannon": ("steel", "special", 80),
    "energy-ball": ("grass", "special", 90), "matcha-gotcha": ("grass", "special", 80),
    "hydro-pump": ("water", "special", 110), "tailwind": ("flying", "status", None),
    "protect": ("normal", "status", None), "clanging-scales": ("dragon", "special", 110),
    "drain-punch": ("fighting", "physical", 75),
}

POKEMON = {
    "garchomp": {"display": "Garchomp", "dex": 445, "types": ["dragon", "ground"],
                 "base": {"hp": 108, "atk": 130, "def": 95, "spa": 80, "spd": 85, "spe": 102},
                 "abilities": ["rough-skin"], "moves": ["earthquake", "dragon-claw", "stone-edge", "protect"]},
    "incineroar": {"display": "Incineroar", "dex": 727, "types": ["fire", "dark"],
                   "base": {"hp": 95, "atk": 115, "def": 90, "spa": 80, "spd": 90, "spe": 60},
                   "abilities": ["intimidate"], "moves": ["flare-blitz", "knock-off", "fake-out", "u-turn"]},
    "rillaboom": {"display": "Rillaboom", "dex": 812, "types": ["grass"],
                  "base": {"hp": 100, "atk": 125, "def": 90, "spa": 60, "spd": 70, "spe": 85},
                  "abilities": ["grassy-surge"], "moves": ["wood-hammer", "grassy-glide", "fake-out", "u-turn"]},
    "amoonguss": {"display": "Amoonguss", "dex": 591, "types": ["grass", "poison"],
                  "base": {"hp": 114, "atk": 85, "def": 70, "spa": 85, "spd": 80, "spe": 30},
                  "abilities": ["regenerator"], "moves": ["spore", "sludge-bomb", "giga-drain", "protect"]},
    "dragonite": {"display": "Dragonite", "dex": 149, "types": ["dragon", "flying"],
                  "base": {"hp": 91, "atk": 134, "def": 95, "spa": 100, "spd": 100, "spe": 80},
                  "abilities": ["multiscale"], "moves": ["extreme-speed", "dragon-claw", "earthquake", "dragon-dance"]},
    "gholdengo": {"display": "Gholdengo", "dex": 1000, "types": ["steel", "ghost"],
                  "base": {"hp": 87, "atk": 60, "def": 95, "spa": 133, "spd": 91, "spe": 84},
                  "abilities": ["good-as-gold"], "moves": ["make-it-rain", "shadow-ball", "protect"]},
    "kingambit": {"display": "Kingambit", "dex": 983, "types": ["dark", "steel"],
                  "base": {"hp": 100, "atk": 135, "def": 120, "spa": 60, "spd": 85, "spe": 50},
                  "abilities": ["supreme-overlord"], "moves": ["kowtow-cleave", "iron-head", "sucker-punch", "protect"]},
    "tyranitar": {"display": "Tyranitar", "dex": 248, "types": ["rock", "dark"],
                  "base": {"hp": 100, "atk": 134, "def": 110, "spa": 95, "spd": 100, "spe": 61},
                  "abilities": ["sand-stream"], "moves": ["rock-slide", "crunch", "high-horsepower", "protect"]},
    "excadrill": {"display": "Excadrill", "dex": 530, "types": ["ground", "steel"],
                  "base": {"hp": 110, "atk": 135, "def": 60, "spa": 50, "spd": 65, "spe": 88},
                  "abilities": ["sand-rush"], "moves": ["high-horsepower", "iron-head", "rock-slide", "protect"]},
    "pelipper": {"display": "Pelipper", "dex": 279, "types": ["water", "flying"],
                 "base": {"hp": 60, "atk": 50, "def": 100, "spa": 95, "spd": 70, "spe": 65},
                 "abilities": ["drizzle"], "moves": ["hurricane", "scald", "weather-ball", "tailwind"]},
    "torkoal": {"display": "Torkoal", "dex": 324, "types": ["fire"],
                "base": {"hp": 70, "atk": 85, "def": 140, "spa": 85, "spd": 70, "spe": 20},
                "abilities": ["drought"], "moves": ["eruption", "heat-wave", "solar-beam", "protect"]},
    "venusaur": {"display": "Venusaur", "dex": 3, "types": ["grass", "poison"],
                 "base": {"hp": 80, "atk": 82, "def": 83, "spa": 100, "spd": 100, "spe": 80},
                 "abilities": ["chlorophyll"], "moves": ["giga-drain", "sludge-bomb", "earthquake", "protect"]},
    "charizard": {"display": "Charizard", "dex": 6, "types": ["fire", "flying"],
                  "base": {"hp": 78, "atk": 84, "def": 78, "spa": 109, "spd": 85, "spe": 100},
                  "abilities": ["solar-power"], "moves": ["heat-wave", "hurricane", "solar-beam", "protect"]},
    "gardevoir": {"display": "Gardevoir", "dex": 282, "types": ["psychic", "fairy"],
                  "base": {"hp": 68, "atk": 65, "def": 65, "spa": 125, "spd": 115, "spe": 80},
                  "abilities": ["trace"], "moves": ["moonblast", "psychic", "shadow-ball", "protect"]},
    "corviknight": {"display": "Corviknight", "dex": 823, "types": ["flying", "steel"],
                    "base": {"hp": 98, "atk": 87, "def": 105, "spa": 53, "spd": 85, "spe": 67},
                    "abilities": ["mirror-armor"], "moves": ["brave-bird", "body-press", "iron-head", "tailwind"]},
    "milotic": {"display": "Milotic", "dex": 350, "types": ["water"],
                "base": {"hp": 95, "atk": 60, "def": 79, "spa": 100, "spd": 125, "spe": 81},
                "abilities": ["competitive"], "moves": ["scald", "ice-beam", "hydro-pump", "protect"]},
    "sneasler": {"display": "Sneasler", "dex": 903, "types": ["fighting", "poison"],
                 "base": {"hp": 80, "atk": 130, "def": 60, "spa": 40, "spd": 80, "spe": 120},
                 "abilities": ["unburden"], "moves": ["close-combat", "dire-claw", "fake-out", "protect"]},
    "dragapult": {"display": "Dragapult", "dex": 887, "types": ["dragon", "ghost"],
                  "base": {"hp": 88, "atk": 120, "def": 75, "spa": 100, "spd": 75, "spe": 142},
                  "abilities": ["clear-body"], "moves": ["dragon-darts", "phantom-force", "u-turn", "protect"]},
    "abomasnow": {"display": "Abomasnow", "dex": 460, "types": ["grass", "ice"],
                  "base": {"hp": 90, "atk": 92, "def": 75, "spa": 92, "spd": 85, "spe": 60},
                  "abilities": ["snow-warning"], "moves": ["blizzard", "giga-drain", "ice-beam", "protect"]},
    "baxcalibur": {"display": "Baxcalibur", "dex": 998, "types": ["dragon", "ice"],
                   "base": {"hp": 115, "atk": 145, "def": 92, "spa": 75, "spd": 86, "spe": 87},
                   "abilities": ["thermal-exchange"], "moves": ["glaive-rush", "icicle-crash", "earthquake", "protect"]},
    "archaludon": {"display": "Archaludon", "dex": 1018, "types": ["steel", "dragon"],
                   "base": {"hp": 90, "atk": 105, "def": 130, "spa": 125, "spd": 65, "spe": 85},
                   "abilities": ["stamina"], "moves": ["electro-shot", "draco-meteor", "flash-cannon", "protect"]},
    "whimsicott": {"display": "Whimsicott", "dex": 547, "types": ["grass", "fairy"],
                   "base": {"hp": 60, "atk": 67, "def": 85, "spa": 77, "spd": 75, "spe": 116},
                   "abilities": ["prankster"], "moves": ["moonblast", "energy-ball", "tailwind", "protect"]},
    "sinistcha": {"display": "Sinistcha", "dex": 1013, "types": ["grass", "ghost"],
                  "base": {"hp": 71, "atk": 60, "def": 106, "spa": 121, "spd": 80, "spe": 70},
                  "abilities": ["hospitality"], "moves": ["matcha-gotcha", "shadow-ball", "protect"]},
    "kommo-o": {"display": "Kommo-o", "dex": 784, "types": ["dragon", "fighting"],
                "base": {"hp": 75, "atk": 110, "def": 125, "spa": 100, "spd": 105, "spe": 85},
                "abilities": ["bulletproof"], "moves": ["clanging-scales", "drain-punch", "close-combat", "protect"]},
}
